data:
  E0: 8000
  batch_size: 64
  chunk_size: 100 MB
  collection: DigitizedRecTrk
  first_threshold: 0.9
  global_stop: 1000000
  global_stop_graph_file: -1
  graph_with_BField: true
  input_dir: /lustre/collider/wanghuayang/DeepLearning/Tracking/trkgnn/Test_root/Merged_Tracker_GNN.root
  input_graph_dir: /lustre/collider/wanghuayang/DeepLearning/Tracking/trkgnn/apply.link.rec/
  min_graph_size: 0.5
  n_workers: 0
  read_from_graph: true
  scale_factor_BField: 100.0
  threshold: 0.4
  tracking_boundary:
    z_max: -7.5
    z_min: -607.75
  tracking_layers:
  - 100.
  - 200.
  - 300.
  - 500.
  - 700.
  - 900.
  tree_name: dp
edge_features: true
loss_func: binary_cross_entropy_with_logits
model:
  edge_input_dim: 4
  heads: 4
  hidden_dim: 64
  n_encoder_layers: 2
  n_iterations: 3
  name: MomNet
  node_input_dim: 6
num_track_predict: false
optimizer:
  learning_rate: 0.004
  lr_decay_schedule:
  - end_epoch: 8
    factor: 0.1
    start_epoch: 4
  - end_epoch: 10
    factor: 0.01
    start_epoch: 8
  - end_epoch: 12
    factor: 0.001
    start_epoch: 10
  - end_epoch: 15
    factor: 0.0001
    start_epoch: 12
  name: Adam
  weight_decay: 1.0e-05
output_dir: ./output.momentum.rec
rndm: 1
task: momentum
training:
  n_total_epochs: 15
