output_dir: ./output
rndm: 1

data:
  #--------------------------------
  # There are two ways to read data:
  # 1. Read from ROOT (default)
  # 2. Read from graph
  #    -- Graph is built from script: `extra_script/graph_to_disk.py`
  #    -- One Graph file is a list of graphs to be one chunk
  #--------------------------------
  # Read from ROOT (disable if read from graph)
  input_dir: "/Users/avencast/CLionProjects/darkshine-simulation/workspace/Tracker_GNN*.root"
  tree_name: 'dp'
  global_stop: 1000000
  chunk_size: "1024 MB"

  # Read from graph
  read_from_graph: true
  input_graph_dir: "/Users/avencast/CLionProjects/darkshine-simulation/workspace/test_output/"
  # global_stop_graph_file: 5

  # General Data Loader Settings
  collection: 'TagTrk1'
  batch_size: 1
  n_workers: 0
  E0: 2900
  min_graph_size: 1 # MB

  # This is mainly for application stage (automatically true)
  #   -- it's more or less determined in the training stage and graph building stage
  #   -- If input graph or trained model has 3 features, then it's trained without BField
  #   -- If input graph or trained model has 6 features, then it's trained with BField
  graph_with_BField: true
  # for scale BField to the order of position
  scale_factor_BField: 100.0

# make sure to choose the correct model if to predict momentum
momentum_predict: false
model:
  name: mpnn
  input_dim: 3 # (x,y,z)
  n_edge_layers: 4
  n_node_layers: 4
  hidden_dim: 64
  n_graph_iters: 8
  layer_norm: true

loss_func: binary_cross_entropy_with_logits

optimizer:
  name: Adam
  learning_rate: 0.001
  weight_decay: 1.e-5
  lr_decay_schedule:
    - { start_epoch: 32, end_epoch: 64, factor: 0.1 }

training:
  n_epochs: 64
  n_total_epochs: 64
